[platformio]
src_dir = SolderingPen_ESP32S2

[env:solderingpen]
platform = espressif32@~6.3.2
board = PTS200
framework = arduino
lib_deps =
  vdeconinck/QC3Control @ ^1.4.1
  olikraus/U8g2 @ ^2.34.17
  madhephaestus/ESP32AnalogRead @ ^0.2.1
  br3ttb/PID @ ^1.2.1
  sparkfun/SparkFun LIS2DH12 Arduino Library @ ^1.0.3
